allowBuilds:
  better-sqlite3: true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true
  workerd: true
nodeLinker: hoisted
peerDependencyRules:
  allowedVersions:
    next: 15.3.8
    vercel: 47.0.4
